# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: rnd_zoiJPl72yKqfKfUWhjQAT2brLc9L
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cs1cei0gph6c73ajh450?key=qtUQ2-I9b7I
          retries: 20
          wait: 16000
          sleep: 30000
